param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "E:\IAR\common\bin\cspybat" -f "K:\BaiduNetdiskDownload\【安富莱电子】STM32-V5开发板HAL库版教程\V5开发板HAL库版教程\1、用户手册，含BSP驱动包设计\V5-000_程序模板\Project\EWARMv8\settings\project.Debug.general.xcl" --backend -f "K:\BaiduNetdiskDownload\【安富莱电子】STM32-V5开发板HAL库版教程\V5开发板HAL库版教程\1、用户手册，含BSP驱动包设计\V5-000_程序模板\Project\EWARMv8\settings\project.Debug.driver.xcl" 
}
else
{
& "E:\IAR\common\bin\cspybat" -f "K:\BaiduNetdiskDownload\【安富莱电子】STM32-V5开发板HAL库版教程\V5开发板HAL库版教程\1、用户手册，含BSP驱动包设计\V5-000_程序模板\Project\EWARMv8\settings\project.Debug.general.xcl" --debug_file=$debugfile --backend -f "K:\BaiduNetdiskDownload\【安富莱电子】STM32-V5开发板HAL库版教程\V5开发板HAL库版教程\1、用户手册，含BSP驱动包设计\V5-000_程序模板\Project\EWARMv8\settings\project.Debug.driver.xcl" 
}
